### ISSUE TITLE
staffmoduleinstances records are missing the module instance ids

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#10]
From Gary.

Could we have some extra info on this one?  They look there to me:

  {
    "STAFF_ID": "5000",
    "MOD_INSTANCE_ID": "MODS101-1-2015S1-0",
    "organisation": "5716480e297d441830b70212",
    "_id": "5718f3403d2ad74c12fc1f55",
    "UPDATED_AT": "2016-04-21T15:35:28.946Z",
    "CREATED_AT": "2016-04-21T15:35:28.946Z",
    "__v": 0
  },

**Comment by amason** [comment]
This is now working as expected - closing this as done.
