### ISSUE TITLE
populate not working on staff - staffModuleInstances

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#11]
See:

 http://78.136.52.242/api/jisc/v1.2.1/staff/56f2ed6a2728db3166445dbd?populate=staffModuleInstances

**Comment by michaelwebbjisc** [comment]
also seems to be the case for:

 http://78.136.52.242/api/jisc/v1.2.1/staff/56f2ed6a2728db3166445dbd?populate=staffCourseInstances

but 

 http://78.136.52.242/api/jisc/v1.2.1/staff/56f2ed6a2728db3166445dbd?populate=mentees does work

**Comment by ht2** [comment]
Thanks @michaelwebbjisc - we've found the bug in the Staff schema on the API and will be part of the v1.2.3 update

**Comment by michaelwebbjisc** [comment]
Confirmed fixed for staffCourseInstance, but superceeded by https://github.com/jiscdev/lrw-udd-api/issues/9
