### ISSUE TITLE
MOD_VLE_MAP doesn't allow more than one module instance to VLE ID

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#12]
Here's a trace of my data load: Note the duplicate key error when I add a second module to VLE_MOD_ID: MODS101

Administrators-MacBook-Air:loader m.webb$ python load.py modulevlemap-123 modulevlemap
http://uojapi2.analytics.alpha.jisc.ac.uk:1341/modulevlemap-123
{"id": "5734a997f18d744b5eb77335", "VLE_MOD_ID": "MODS101", "MOD_INSTANCE_ID": "MODS101-1-2014S1-1", "createdAt": "2016-05-12T16:04:39.505Z", "updatedAt": "2016-05-12T16:04:39.505Z"}
{"MOD_INSTANCE_ID":"MODS101-1-2014S1-1","VLE_MOD_ID":"MODS101","moduleInstance":"573487ec3d4a8c6916b14bfe","_id":"5734a9d89c96f4132528b507","UPDATED_AT":"2016-05-12T16:05:44.771Z","CREATED_AT":"2016-05-12T16:05:44.771Z"}
{"id": "5734a997f18d744b5eb77336", "VLE_MOD_ID": "MODS101", "MOD_INSTANCE_ID": "MODS101-1-2015S1-1", "createdAt": "2016-05-12T16:04:39.577Z", "updatedAt": "2016-05-12T16:04:39.577Z"}
{"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: ll_demo.jiscModuleVleMaps index: organisation_1_VLE_MOD_ID_1 dup key: { : ObjectId('5716480e297d441830b70212'), : \"MODS101\" }","op":{"moduleInstance":"573487ed3d4a8c6916b14bff","CREATED_AT":"2016-05-12T16:05:44.876Z","UPDATED_AT":"2016-05-12T16:05:44.876Z","MOD_INSTANCE_ID":"MODS101-1-2015S1-1","VLE_MOD_ID":"MODS101","organisation":"5716480e297d441830b70212","_id":"5734a9d89c96f4132528b508","__v":0}}
Administrators-MacBook-Air:loader m.webb$ python remove.py  modulevlemap

**Comment by andrewhickey** [comment]
Fixed

**Comment by amason** [comment]
Reviewed and is working as expected. Closing.
