### ISSUE TITLE
studentmoduleinstance not completing studentCourseMembership

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#13]
Example:

 {
    "STUDENT_ID": "92654628",
    "STUDENT_COURSE_MEMBERSHIP_ID": "92654628-S000A",
    "STUDENT_COURSE_MEMBERSHIP_SEQ": "1",
    "COURSE_INSTANCE_ID": "S000A-2015A",
    "MOD_INSTANCE_ID": "MODS101-1-2015S1-1",
    "MOD_RESULT": 3,
    "MOD_RETAKE": null,
    "MOD_START_DATE": "2016-01-01T00:00:00.000Z",
    "MOD_END_DATE": "2016-05-31T23:00:00.000Z",
    "MOD_FIRST_MARK": null,
    "MOD_ACTUAL_MARK": null,
    "MOD_AGREED_MARK": null,
    "MOD_FIRST_GRADE": "",
    "MOD_ACTUAL_GRADE": "",
    "MOD_AGREED_GRADE": "",
    "MOD_CREDITS_ACHIEVED": "",
    "MOD_CURRENT_ATTEMPT": "",
    "MOD_COMPLETED_ATTEMPT": "",
    "X_MOD_NAME": "BASIC ODS 1",
    "student": "573484843d4a8c6916b14a85",
    "moduleInstance": "573487ed3d4a8c6916b14bff",
    "courseInstance": "573488173d4a8c6916b14c05",
    "studentCourseMembership": null,
    "_id": "5734901e3d4a8c6916b14f05",
    "UPDATED_AT": "2016-05-12T14:15:58.869Z",
    "CREATED_AT": "2016-05-12T14:15:58.869Z"
  },

Should match to:

"STUDENT_ID": "92654628",
    "STUDENT_COURSE_MEMBERSHIP_ID": "92654628-S000A",
    "STUDENT_COURSE_MEMBERSHIP_SEQ": "1",
    "COURSE_ID": "S000A",
    "WITHDRAWAL_REASON": 97,
    "WITHDRAWAL_DATE": null,
    "ENTRY_QUALS": "P50",
    "COURSE_OUTCOME": null,
    "COURSE_GRADE": null,
    "COURSE_AIM_ATTAINED": "X99",
    "COURSE_MARK": null,
    "COURSE_EXPECTED_END_DATE": "2016-06-01T00:00:00.000Z",
    "COHORT_ID": "1",
    "student": "573484843d4a8c6916b14a85",
    "course": null,
    "_id": "57349f363dbb496f1202812c",
    "UPDATED_AT": "2016-05-12T15:20:23.001Z",
    "CREATED_AT": "2016-05-12T15:20:23.001Z"
  },

**Comment by andrewhickey** [comment]
Fixed now

**Comment by amason** [comment]
SSP advised this is no longer an issue. Closing.
