### ISSUE TITLE
Student course membership not relating to course

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#14]
eg:

{
    "STUDENT_ID": "90006516",
    "STUDENT_COURSE_MEMBERSHIP_ID": "90006516-S000A",
    "STUDENT_COURSE_MEMBERSHIP_SEQ": "1",
    "COURSE_ID": "S000A",
    "WITHDRAWAL_REASON": 97,
    "WITHDRAWAL_DATE": null,
    "ENTRY_QUALS": "P50",
    "COURSE_OUTCOME": null,
    "COURSE_GRADE": null,
    "COURSE_AIM_ATTAINED": "X99",
    "COURSE_MARK": null,
    "COURSE_EXPECTED_END_DATE": "2016-06-01T00:00:00.000Z",
    "COHORT_ID": "1",
    "student": "573484b33d4a8c6916b14b2a",
    "course": null,
    "_id": "57349f483dbb496f120281d1",
    "UPDATED_AT": "2016-05-12T15:20:40.055Z",
    "CREATED_AT": "2016-05-12T15:20:40.055Z"
  },

should relate to:

  {
    "COURSE_ID": "S000A",
    "SUBJECT": "G100",
    "TITLE": "BSc General",
    "COURSE_AIM": "H00",
    "INST_TIER_1": "Faculty of Science",
    "INST_TIER_2": "Department of General",
    "INST_TIER_3": "School of General",
    "courseInstances": [
      "573488163d4a8c6916b14c04",
      "573488173d4a8c6916b14c05",
      "573488183d4a8c6916b14c06"
    ],
    "studentCourseMemberships": [],
    "_id": "5734866a3d4a8c6916b14bf3",
    "UPDATED_AT": "2016-05-12T13:34:34.063Z",
    "CREATED_AT": "2016-05-12T13:34:34.063Z"
  }

and visa versa

**Comment by andrewhickey** [comment]
Fixed now

**Comment by amason** [comment]
SSP advised this is no longer an issue. Closing.
