### ISSUE TITLE
Expect DASH_SHIB_ID for staff to match pid

### ISSUE THREAD

**Issue by gryglbrt** [jiscdev/lrw-udd-api#16]
It looks like staff_id = 5000 is intended to map to UK Federation test account "beth" 

It was expected that the DASH_SHIB_ID would match the UK Federation pid value = https://test-idp.ukfederation.org.uk/idp/shibboleth!https://sp.data.alpha.jisc.ac.uk/shibboleth!aaeBgvZdXL8Rrj1dyb9UJ1Njpjg= in beth's case. 

Current record:

      "STAFF_ID": "5000",
        "FIRST_NAME": "Beth",
        "LAST_NAME": "Obrien",
        "TITLE": "Dr",
        "PRIMARY_EMAIL_ADDRESS": "Beth.Obrien@mwebb.me.uk",
        "HESA_STAFF_ID": "10005000",
        "DASH_SHIB_ID": "'beth@test.ukfederation.org.uk','b2@test.ukfederation.org.uk'",

**Comment by michaelwebbjisc** [comment]
You were there while I was still populating :-)

I'll just putting the documentation together, but there's a slight change to how this handled to accomodate both SSP and Dashboard.  We'll probably want to change this to a more elegant solution in a future vresion of the UDD.

If you look now you will see it says:

  "DASH_SHIB_ID": "'beth@test.ukfederation.org.uk','https://test-idp.ukfederation.org.uk/idp/shibboleth!https://sp.data.alpha.jisc.ac.uk/shibboleth!aaeBgvZdXL8Rrj1dyb9UJ1Njpjg='",

This is a little inelegant, but will work for both SSP (which will only work with the eppn) and dashboards (which will get the pid).

So the query is slightly different now, but if you have either the pid or eppn you do a regex query like this:

 http://78.136.52.242/api/jisc/v1.2.3/staff?query={"DASH_SHIB_ID": {"$regex" : "'duns@test.ukfederation.org.uk'"}} 

or:

 http://78.136.52.242/api/jisc/v1.2.3/staff?query={"DASH_SHIB_ID": {"$regex" : "https://test-idp.ukfederation.org.uk/idp/shibboleth!https://sp.data.alpha.jisc.ac.uk/shibboleth!aaeBgvZdXL8Rrj1dyb9UJ1Njpjg='"}}

Make sure you include the ' round the thing you are looking for so you don't get falso positives.

**Comment by gryglbrt** [comment]
Looks good. Thanks Michael.

Amanda, you can close this out.
