### ISSUE TITLE
One more Module VLE Map record

### ISSUE THREAD

**Issue by gryglbrt** [jiscdev/lrw-udd-api#18]
Also need VLE_MOD_ID = 4 so we can both UofJisc (LA 101, 102) Moodle courses.

**Comment by amason** [comment]
Michael - any update on this one?

**Comment by amason** [comment]
@michaelwebbjisc  - we only need the VLE_MOD_ID = 4 only if Jisc wants to demo from different courses. If the one course is sufficient, we can close this out.
