### ISSUE TITLE
Aggregate API error: "aggregation result exceeds maximum document size"

### ISSUE THREAD

**Issue by russtrotter** [jiscdev/lrw-udd-api#19]
I'm trying to see what the broadest pipeline I can specify to the aggregate to get the widest activity coverage, e.g. here's the pipeline JSON:

[
{
	"$match" : {
		
	}
}
]

 but getting the error message indicated in the description.

Is there a more appropriate usage we should be specifying? e.g. filter by certain XAPI verbs?

**Comment by andrewhickey** [comment]
Discussed via email but the answer was

> 
> As a simple fix you could add a limit stage. Otherwise you could add a time range using the $dte operator on timestamp.
> 
> something like this
> 
> [
>   {"$match": 
>     { "timestamp": {"$gte": { "$dte": "2015-11-04T00:00:00"}}}
>   },
>   {"$limit": 50}
> ]
