### ISSUE TITLE
API Validation - Course Entity (UDD 1.2.3)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#20]
Dear HT2 (and all!),

The following COURSE entity fields are indeed optional in UDD 1.2.3 (correct!), but currently the API validation is requiring values for all of them (I'm using UDDloader).

INST_TIER_1
INST_TIER_2
INST_TIER_3

https://github.com/jiscdev/analytics-udd/blob/master/udd/course.md

Many Thanks,

Rob

**Comment by andrewhickey** [comment]
Fixed now

**Comment by robwynj** [comment]
Thanks Andrew :)

**Comment by amason** [comment]
Closing this out since it is fixed.
