### ISSUE TITLE
aggregate API: getting truncated output and text/html content type

### ISSUE THREAD

**Issue by russtrotter** [jiscdev/lrw-udd-api#21]
Here's the pipeline i'm using:

[{"$match":{"statement.object.id":{"$ne":"https://lap.jisc.ac.uk/earlyAlert/unicon/id"},"statement.stored":{"$gte":"2015-12-12T15:20:07.129300Z","$lt":"2015-12-12T21:20:07.129300Z"}}}]

server responds with with a text/html message, but the only data i get is 5 bytes:

<CR><LF>{<CR><LF>

so it's looking like data starts to process, but then some error (that doesn't get returned in the HTTP response) happens

Also, this error doesn't happen all the time. When it does work, it returns about 4700 statements.  I suspect its another overflow of either the 100 mb pipeline stage or the 16mb aggregation result

**Comment by amason** [comment]
Closing this as we have worked around it. If we run into any other issues - I will re-open.
