### ISSUE TITLE
API Validation - Student on Assessment Instance Entity (UDD 1.2.3)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#22]
Dear HT2/ All,

Validation does not perform as expected for the ASSESSMENT_RESULT field in SoAI entity in UDD 1.2.3. 

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_assessment_instance.md#assessment_result

Should allow values 1-4 inclusive, for this mandatory field collection (max value in validation feedback,is currently specified as 2...).

Kind Regards

Rob

**Comment by andrewhickey** [comment]
Fixed now.

**Comment by robwynj** [comment]
Thanks Andrew :)

**Comment by amason** [comment]
Closing this out since its fixed.
