### ISSUE TITLE
Demo data issue: MAX_POINTS

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#23]
The MAX_POINTS value is a String and currently has "one" for most assessments in the demo data in LRW. 

For this data set it should be 100.

**Comment by amason** [comment]
Hi Michael - Is this issue still needed?

**Comment by amason** [comment]
@michaelwebbjisc - I don't think this issue is needed anymore and I think you can close. Since I just created the MAX_MARKS issue....I think this one is obsolete. If so, can you close this one out?
