### ISSUE TITLE
API UDD 1.2.4 - STUDENT entity - TUTOR_STAFF_ID should be optional not mandatory?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#31]
Hi,

Can you check this please? Should be optional as per UDD.

Many Thanks

Rob

**Comment by ht2** [comment]
You're correct, this will be patched into 1.2.4 via tomorrow's push

**Comment by robwynj** [comment]
Brilliant! Thanks for this. Can you confirm 1.2.4 and then also 1.2.5, 1.2.6 (and when?) will be up-to-date and available for API validation purposes.

Many Thanks/ Kind Regards

Rob

**Comment by ht2** [comment]
Yes, they will all inherit changes from previous versions and I'll make sure to go back through and patch subsequents in cases like this. 1.2.4 and 1.2.5 will definitely have this amendment (as well as the optional USERNAME, FIRST_NAME, LAST_NAME) and both will be released tomorrow. 

Still waiting for confirmation of 1.2.6, but that is looking unlikely to be closed in time for me to patch in for tomorrow's update.

**Comment by robwynj** [comment]
Brilliant - Thanks James. Yes tomorrow for 1.2.4/.5 is fab.

Many Thanks

Rob
