### ISSUE TITLE
ASSESSMENTINSTANCE.ASSESS_WEIGHT - API Validation (0-100 or 0-1 (fraction of 1))

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#32]
Hi Andrew/ James,

Can you confirm if ASSESS_WEIGHT validation in the API is based on a value of 0-100 or is it decimal (a fraction of 1 eg. 20% weighting, would be 0.2).

Many Thanks

Rob

**Comment by ht2** [comment]
Hi Rob,

It's set to be a with a min value of 0 and a max value of 100. I believe that is correct? https://github.com/jiscdev/analytics-udd/blob/v1.2.5/udd/assessment_instance.md#assess_weight

**Comment by amason** [comment]
Hi @robwynj  - I talked to Andrew and it is et to be a min value of 0 and a max value of 100. Do you need Andrew to change anything with this or is this sufficient? If sufficient, we can probably close out this issue as complete.
