### ISSUE TITLE
Issue with Values in LRW for Test User

### ISSUE THREAD

**Issue by amason** [jiscdev/lrw-udd-api#34]
Hi Andrew,

When I test with the following user creds below, I'm being redirected to the Jisc Login Registration page. 

U: beth
P: passwordb

I'm think the data has been changed in the lrw.

Value in the LRW:

 "DASH_SHIB_ID": "'beth@test.ukfederation.org.uk','https://test-idp.ukfederation.org.uk/idp/shibboleth!https://sp.data.alpha.jisc.ac.uk/shibboleth!aaeBgvZdXL8Rrj1dyb9UJ1Njpjg='"

Value we get from IDP:

 "DASH_SHIB_ID": "'beth@test.ukfederation.org.uk','https://test-idp.ukfederation.org.uk/idp/shibboleth!https://sp.data.alpha.jisc.ac.uk/shibboleth!gsTtK02bDaksVnMOIoGUeoRbQ0w='"

We need the value we get from the LRW to match (or at least contain) what is in the IDP. Can you help me on this one?

**Comment by andrewhickey** [comment]
Hi Amanda,

A few questions,

What page are you testing?
Are you looking for me to update a record in the LRW? 
If so can you let me know what API credentials you are using via email?

Thanks!

**Comment by amason** [comment]
Hi Andrew,

This is the flow I'm using to test:
Click on this URL: http://ec2-52-18-120-29.eu-west-1.compute.amazonaws.com:8080/login
Choose University of Jisc. Click Sign In.
Enter these creds:
U: beth
P: passwordb

Notice that I'm taken to the Jisc Login Registration page. 

So the problem is with the idp for beth. I just need beth to be registered with the UK Fed like she was before if that helps at all. If not, let me know and I can provide me details.

Thanks!

**Comment by andrewhickey** [comment]
Hi Amanda,

After a quick chat with Gary today I've updated Beth's DASH_SHIB_ID in the LRW. The login flow seems to work now.

**Comment by amason** [comment]
I confirmed this is working accurately now! Thank you! Closing this as fixed!
