### ISSUE TITLE
UDD API 1.2.6 - Not yet live and in service?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#35]
FAO: HT2

I know that UDD 1.2.6 was due to be live and in-service a few weeks ago, but am unable to see this when using postman + Tribal mentioned it this morning too.

Can you advise?

Many Thanks

Rob

**Comment by ht2** [comment]
Hi Rob, sorry, this slipped I guess. I don't think a formal date was ever set, the PR for 1.2.6 got merged but no further action was taken whilst there the pen-testing was happening.

We'll look to resolve and get the version pushed in the next couple of days

**Comment by robwynj** [comment]
No worries - it was mentioned I think to be done a couple of weeks ago, but totally understand :)

If you can do this ASAP, that would be great, as need to validate further datasets now based on HEIs coming in for 1.2.6 :)

Many Thanks

Rob

**Comment by ht2** [comment]
No prob, working on it this affo

**Comment by amason** [comment]
Let me know when v1.2.6 is fully executed and in place. We just did the work to conform to v1.2.5. We will want to update to V1.2.6 when HT2 says it's ready. I know the changes are minimal, but we would like to ensure we are in line with the latest UDD version.

**Comment by ht2** [comment]
Hi all, we are looking to push out the v1.2.6 update to the site today. Can I also confirm we are happy to bump the `/stable` endpoint to point at the new version as well?

**Comment by robwynj** [comment]
Good with me. Ideal timing, as will hopefully start to validate another HEIs data tomorrow.

Many Thanks

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860

**Comment by ht2** [comment]
One other feature to note in this release, relations between models will now automatically be removed when the model is updated/removed. I know this is something @michaelwebbjisc had requested

**Comment by ht2** [comment]
Hi all,

I can confirm that v1.2.6 is live and the stable UDD URL now points at that version:

https://jiscv2.learninglocker.net/api/jisc/stable/about

```
{
  "version": "1.2.6"
}
```

**Comment by robwynj** [comment]
Brilliant ☺ Thanks James. Will start uploading tomorrow AM.

Cheers

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860
