### ISSUE TITLE
UDD API 1.2.6 - COURSE.SUBJECT not allowing M000 and W000 codes?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#39]
Hia,

Got this problem with importing subject codes M000 and W000, being denoted as invalid. Can you check this for me please - Many Thanks.

Kind Regards

Rob

**Comment by robwynj** [comment]
I suspect this will also affect the SUBJECT codings for the MODULE entity too (MOD_SUBJECT)?

Kind Regards

Rob

**Comment by robwynj** [comment]
Can you chase this for me please - it is prohibiting me uploading data to the LRW :)

Many Thanks!

Rob

**Comment by robwynj** [comment]
Can we have an ETA on this fix please :)

Many Thanks

Rob

**Comment by andrewhickey** [comment]
Hi Rob, this will be fixed by Friday afternoon.

**Comment by andrewhickey** [comment]
I can't find M000 and W000 in https://www.hesa.ac.uk/support/documentation/jacs/jacs3-detailed but I've added them.

Changes aren't live yet. Just doing that now.

**Comment by andrewhickey** [comment]
Changes should be live if you want to test. I'm trying to get back into my postman account to do the same.

**Comment by robwynj** [comment]
Fab – Thanks Andrew, legend  ☺

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860
