### ISSUE TITLE
updatedDt 

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#4]
* is updatedDt field a valid field for the objects that get returned from these API’s?  it’s hard to tell from the unfiltered view since the API doesn’t return that kind of meta data as it stands

**Comment by amason** [comment]
Per Andrew, he advised the following: The fields are UPDATED_AT and CREATED_AT. You should be getting those back unless it's filtered by the scope on your particular API credentials. I'll look into it.

In working with Russ - this is what we needed and issue can be closed out as resolved. @michaelwebbjisc please close this out.
