### ISSUE TITLE
Ability to store/ retrieve LAP alerts and related data within the LRW

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#40]
Question of whether these alerts would be stored in an additional relational UDD table or via xAPI (LRW).

This will be key to the integration piece for 3rd party CRMs (instead of Unicon SSP for example) and also to receive/ store resultant actions from HEI CRMs against those intervention alerts too (so would have to be bi-directional). So the LAP alerts will need to be stored, along with metrics information too eg. GPA, Engagement etc?

Same would go for the student app's self-declared data too (stored via LRW/ linked to UDD?).

**Comment by gryglbrt** [comment]
The data that drives whether an alert is sent or not is already stored in the LRW (see https://github.com/jiscdev/xapi/blob/master/lap/apereo/model_output.md). The distinction here is that the model results for all students are available in the LRW and not just those at academic risk (and thus would have received an early alert in ssp).

Additional details (private confluence):

- https://jisc-la.atlassian.net/wiki/display/JLA/Final+Output+Table+to+xAPI
- https://jisc-la.atlassian.net/wiki/display/JLA/Final+Output+xAPI+Examples+and+Queries

-
