### ISSUE TITLE
UDD API 1.2.6 - MODULE.MOD_SUBJECT / COURSE.SUBJECT - Y000 and L000 codes not allowed for load

### ISSUE THREAD

**Issue by robwynj** [jiscdev/lrw-udd-api#41]
Hia,

Can you check these issues for me please - is there a wider issue with ?000 codes for these fields, which might need checking too (just incase!).

Many Thanks,

Rob

**Comment by andrewhickey** [comment]
Hi Rob, The issue will be that the only codes we've allowed are those listed on  https://www.hesa.ac.uk/support/documentation/jacs/jacs3-detailed. Is there a different source we should be pulling from? I'll add Y000 and L000 tomorrow morning :)

**Comment by robwynj** [comment]
Hi Andrew,

FYI below - may need to double check with Wilbert, but this is the coding I see HEIs using:

https://www.hesa.ac.uk/collection/c15051/a/sbjca/

FYI @huwrobertsjisc 

Kind Regards

Rob

**Comment by andrewhickey** [comment]
Morning Rob, I've updated the list of allowed subject codes to be https://www.hesa.ac.uk/collection/c15051/a/sbjca/
