### ISSUE TITLE
Method for updating/removing extensions in a model

### ISSUE THREAD

**Issue by ht2** [jiscdev/lrw-udd-api#45]
Hi all, we are pushing forward with extensions here at the moment. 

### Creating extensions
Currently we envision that when you POST to a model, you will be able to send a structure like this:

```
POST /models/course
{
  "COURSE_ID": "COURSE_1",
  "SUBJECT": "Test course",
  "extensions": {
    "ht2": {
        "live": true,
        "estimatedHours": 40
    }
  }
}
```

Where:
* `ENTITY` = `course` 
* `REF_KEY` = `"COURSE_1"`.
* `CONTROLLER` = `ht2` (formally `ORGANISATION`, `CONTROLLER` key name [proposed here](https://github.com/jiscdev/analytics-udd/issues/188))
* `PROPERTY_NAME` = `"live"`
* `PROPERTY_VALUE` = `true`

### Updating extensions
If additional extensions are required, or values need to be changed, then a POST or PATCH would then be used to send a valid request:

```
POST or PATCH /models/course/COURSE_1
{
  "extensions": {
    "ht2": {
        "live": false,
        "totalEnrolments": 9000
    },
    "jisc": {
        "foo": "bar" 
    }
  }
}
```

The result of this would be:
```
{
  "COURSE_ID": "COURSE_1",
  "SUBJECT": "Test course",
  "extensions": {
    "ht2": {
        "live": false,
        "estimatedHours": 40,
        "totalEnrolments": 9000
    }
    "jisc": {
        "foo": "bar" 
    }
  }
}
```

### Removing extensions
When it comes time to remove an extension, things get a bit more difficult. We do not want to simply "delete by omission", as this would require the CONTROLLER to send in the complete list of extensions on every request. 

Instead, I would propose a system that is already used in the [State API component of xAPI](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#json-procedure-with-requirements). 

This states that a `POST` to the model will merge changes, whereas a `PUT` to the model will replace changes. Unless there is a need for it to apply across the entire model, I think we can limit this behaviour to the extensions only (and even then, keep it within an CONTROLLER's).

So, if I was looking to remove the `"estimatedHours"` extension from the above example, I would need to:

```
PUT /models/course/COURSE_1
{
  "extensions": {
    "ht2": {
        "live": true,
        "totalEnrolments": 9000
    }
  }
}
```

The returned model would look like:
```
{
  "COURSE_ID": "COURSE_1",
  "SUBJECT": "Test course",
  "extensions": {
    "ht2": {
        "live": true,
        "totalEnrolments": 9000
    }
    "jisc": {
        "foo": "bar" 
    }
  }
}
```

Note how the `jisc` CONTROLLER's extensions have not been amended. Unless the namespace is fully resolved in the PUT data, other extensions are left alone. The PUT only acts on defined CONTROLLER extensions in the body of the PUT request.

How do people feel about that as a process? The alternative is to only allow a client to `null` an extension, and never actually remove the key.

**Comment by alanepaull** [comment]
In extensions.md the reference is REF_KEY, rather than REF_ID.
Now agreed that AGENT above will be CONTROLLER, to avoid confusion with xAPI Agent.

**Comment by ht2** [comment]
Thanks @alanepaull, I've updated the above

**Comment by ryansmith94** [comment]
Conclusion from the call today:
No need to delete extensions right now. If they need to be removed, they can be nulled by the controller.

@ht2
