### ISSUE TITLE
Cascade deletions on extensions

### ISSUE THREAD

**Issue by ht2** [jiscdev/lrw-udd-api#46]
Hi all,

When an entity is (force) DELETED do we want the default action for extensions to be:

* a CASCADE, that removes all extensions for that specific entity
* set all the extensions for that specific entity to `null`, therefore keeping the CONTROLLER's extension keys if the model was ever recreated with the same primary ID
* leave all extensions as they are, recreating the specific entity would mean that existing extensions were present again. Removal of extensions could then be handled on a per CONTROLLER basis depending on the outcome of #45 

James

**Comment by ht2** [comment]
In addition, should a soft deleted entity set all extensions to null (given that all fields are null'd on soft delete in the entity currently)

**Comment by ryansmith94** [comment]
Conclusion from call today:
1. Yes delete extensions when entity is hard deleted.
2. Yes null extensions when entity is soft deleted.

**Comment by ryansmith94** [comment]
@ht2

**Comment by ryansmith94** [comment]
Reopened until this is implemented

**Comment by gmoger-jisc** [comment]
Can we please look to implement this?  We have no way of removing extensions that are no longer needed.

**Comment by ryansmith94** [comment]
Yeah, I'll discuss with @ht2 today 👍

**Comment by ht2** [comment]
OK - let's put back into the schedule as a todo. Do we feel we have everything we need to move forward?

**Comment by ryansmith94** [comment]
I think we just need a database migration to add the cascade for force deletes if you agree James?

**Comment by ht2** [comment]
@gmoger-jisc Just need some clarification - are you simply looking to remove individual extensions on a model, or are you concerned about removing extensions on soft and hard deleted models too?

**Comment by gmoger-jisc** [comment]
I just want some mechanism to remove a single or all extensions on a record. This would be with forced delete as we no longer use the soft delete function.

**Comment by ryansmith94** [comment]
Hey @gmoger-jisc, thanks for the reply. Sorry to be finicky, can you please confirm which of the features below you need?

1. Extensions deleted automatically when the record they're attached to is (force) deleted.
2. Extensions deleted manually via the API.

**Comment by gmoger-jisc** [comment]
I hadn't realised the 1st point didn't happen already. The 2nd is what I was looking for originally but both should be in place.

**Comment by ryansmith94** [comment]
Okay, thanks for the clarification. Yeah I don't think the 1st point happens already, I think we put off doing that for a little bit to see how things went with extensions when they were first released.

**Comment by ryansmith94** [comment]
Hey Gareth, some amendments to my earlier comments. What currently happens.

1. On soft deletes, all extensions are nulled.
2. On force deletes, all extensions are deleted.

Proposed changes.

1. On soft deletes, extensions are left as is (because if you restore a soft deleted record, you'd have to add all the extensions back.
2. When updating extensions with null we delete the extension.

Are you happy with those proposed changes?

**Comment by gmoger-jisc** [comment]
Yes, changes are fine.

**Comment by ryansmith94** [comment]
Ok thanks Gareth, I have a PR waiting for QA now.

**Comment by ryansmith94** [comment]
Hey Gareth, that's been deployed now.
