### ISSUE TITLE
studentidmap missing from Available entity endpoints?

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/lrw-udd-api#48]
We stated that technically the studentidmap isn't part of the UDD, although it's documented in a similar fashion. However, it's currently missing from the "Available entity endpoints" list in documentation.md. Should it be in that list, as /models/studentidmap?

**Comment by ryansmith94** [comment]
Yeah it should, I think it's missing because it wasn't actually there when we wrote those docs (we were waiting for a primary key to be decided).
