### ISSUE TITLE
STUDENT_ID_MAP missing column

### ISSUE THREAD

**Issue by arc12** [jiscdev/lrw-udd-api#49]
A query on /studentidmap gives me an error:

select `studentIdMap`.`STUDENT_ID_MAP_ID`, `studentIdMap`.`STUDENT_ID`, `studentIdMap`.`DOMAIN`, `studentIdMap`.`IDENTIFIER`, `studentIdMap`.`DELETED_AT`, `studentIdMap`.`CREATED_AT`, `studentIdMap`.`UPDATED_AT`, `studentIdMap`.`deleted`, `studentIdMap`.`STUDENT_ID_MAP_ID` from `studentIdMap` where `studentIdMap`.`organisation` = '577149e3c2cb35655edf0991' and `studentIdMap`.`deleted` = false - ER_BAD_FIELD_ERROR: Unknown column 'studentIdMap.CREATED_AT' in 'field list'

**Comment by ht2** [comment]
Yep, good spot - I've added this to the production database and amended the code base
