### ISSUE TITLE
Sub Clauses

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#5]
Does the query syntax support additional clauses, e.g. if i wanted to query a *range* of updatedDt’s, the logical equiv of ($gte low AND $lt high)

**Comment by amason** [comment]
I received feedback from Andrew advising this:

Yep https://jiscv2.learninglocker.net/api/jisc/v1.2.1/student?populate="studentAdditional"&query={"UPDATED_AT":{"$gte":"2016-05-01T00:00:00.000Z","$lt":"2016-05-10T00:00:00.000Z"}}

**Comment by amason** [comment]
In working with Russ - this answers his question. Closing this out as the issue is resolved.
