### ISSUE TITLE
?select not consistent with jiscv2 (1.2.*) API

### ISSUE THREAD

**Issue by arc12** [jiscdev/lrw-udd-api#50]
On the jiscv2 UDD LRW we had, for example:
/institution?select={"students":0}

This fails with a type error on jiscudd, although this works:
/institution?select={"students":false}

Could we confirm support for ?select remains.
If so, could we also have values of 1 and 0 functioning as booleans, so that the same query works across both.

**Comment by ht2** [comment]
I'll need to double check that - shouldn't be a problem. 

FYI, @ryansmith94 is actually on annual leave now until June 5th. Where possible I will triage and make changes, but if non-critical it may get pushed until then.

**Comment by arc12** [comment]
turns out true/false can be used on the old LRW.

**Comment by ht2** [comment]
Ah, that makes sense - think @ryansmith94 explicitly set this to be a boolean as thats how the old middleware required it. Probably those 0/1 values were just being cast somewhere along the lines into a boolean value, but if we can just stick with true/false that would be good
