### ISSUE TITLE
Student Course Membership Query Bug

### ISSUE THREAD

**Issue by arc12** [jiscdev/lrw-udd-api#52]
simple query with no additional parameters give a 500 error and message:

select `studentCourseMembership`.`STUDENT_COURSE_MEMBERSHIP_ID`, `studentCourseMembership`.`STUDENT_ID`, `studentCourseMembership`.`COURSE_ID`, `studentCourseMembership`.`WITHDRAWAL_REASON`, `studentCourseMembership`.`ENTRY_QUALS`, `studentCourseMembership`.`ENTRY_POINTS`, `studentCourseMembership`.`COURSE_OUTCOME`, `studentCourseMembership`.`COURSE_GRADE`, `studentCourseMembership`.`COURSE_AIM_ATTAINED`, `studentCourseMembership`.`COURSE_MARK`, `studentCourseMembership`.`COURSE_EXPECTED_END_DATE`, `studentCourseMembership`.`COURSE_END_DATE`, `studentCourseMembership`.`COURSE_DURATION`, `studentCourseMembership`.`COURSE_JOIN_DATE`, `studentCourseMembership`.`COURSE_JOIN_AGE`, `studentCourseMembership`.`COHORT_ID`, `studentCourseMembership`.`ACTIVE_MEMBERSHIP`, `studentCourseMembership`.`PREDICTED_OUTCOME_GRADE`, `studentCourseMembership`.`ATTAINMENT_TARGET_GRADE`, `studentCourseMembership`.`PREDICTED_OUTCOME_MARK`, `studentCourseMembership`.`ATTAINMENT_TARGET_MARK`, `studentCourseMembership`.`PRIOR_GRADE_ENGLISH`, `studentCourseMembership`.`PRIOR_GRADE_MATHEMATICS`, `studentCourseMembership`.`INITIAL_ASSESSMENT_ENGLISH`, `studentCourseMembership`.`INITIAL_ASSESSMENT_MATHEMATICS`, `studentCourseMembership`.`DELETED_AT`, `studentCourseMembership`.`CREATED_AT`, `studentCourseMembership`.`UPDATED_AT`, `studentCourseMembership`.`deleted`, `studentCourseMembership`.`STUDENT_COURSE_MEMBERSHIP_ID` from `studentCourseMembership` where `studentCourseMembership`.`organisation` = '577149e3c2cb35655edf0991' and `studentCourseMembership`.`deleted` = false - ER_BAD_FIELD_ERROR: Unknown column 'studentCourseMembership.COURSE_DURATION' in 'field list'

**Comment by ht2** [comment]
Thanks, looks like `COURSE_DURATION` has been used in the model where the schema just has `DURATION`. I'll reference the v1.3.0 spec and see which is the correct field.

**Comment by ht2** [comment]
OK, it should be `COURSE_DURATION` - nice simple fix, just need to amend the schema which is now done. Can you try again?

**Comment by arc12** [comment]
queries OK now
Thanks
