### ISSUE TITLE
Best way to batch retrieve data

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#53]
One for @ht2 - what's the best way to batch download data? ie when we wanted to get the whole data before we did it on batches with _id

Apologies if this is answered somewhere else!

**Comment by arc12** [comment]
@michaelwebbjisc - I did it in basically the same way but with a look-up of what the singular "primary key" is for each entity, and used that instead of "_id"
The same sort={} clause forumation works

Would have been nice to have "_id" available on all entities but I couldn't wait for that to be implemented (if ever)

**Comment by ht2** [comment]
Hey guys - yes, the old approach of batching via the primary key will be the best method. I'd expect you to see some good results in terms of how many you can fetch per batch, but given you are first to truly use this in anger it will be interesting to see what results you get and if/where there are any pinch points.  Obviously the primary keys will be indexed (as is default in MySQL) so you should get good results, but there is an additional filter based on the organisation tied to your credentials, so I will jump in and ensure that is indexed efficiently as well. 

Do let me know how you get on, will be intrigued to know what (if!) there are any limitations around this.

**Comment by ht2** [comment]
OK, I've double checked and the primary index is correctly set against `organisation` _and_ the primary key for each model, so you should have no problems using that for batching with upmost efficiency.

**Comment by michaelwebbjisc** [comment]
thanks!
