### ISSUE TITLE
LRW API query result sort order?

### ISSUE THREAD

**Issue by russtrotter** [jiscdev/lrw-udd-api#6]
- Does the LRW return results in a default sorted order?
- Does the LRW api 'pipeline' parameter have syntax to specify a field and sort order?

**Comment by amason** [comment]
Andrew advised the following:

Q: Does the LRW return results in a default sorted order? 
A: The udd and statement aggregation apis don't have a guaranteed sort order. 

Q: Does the LRW api 'pipeline' parameter have syntax to specify a field and sort order?  
A: The udd apis can be sorted as follows 
GET /student?sort=name
GET /student?sort=-name
GET /student?sort={"name":1}
GET /student?sort={"name":0}

The aggregation api pipeline parameter can have as many $sort stages as you need.
https://docs.mongodb.com/manual/reference/operator/aggregation/sort/

**Comment by michaelwebbjisc** [comment]
thanks - will mark this one as closed.
