### ISSUE TITLE
Need UPDATED_AT field available in UDD API output

### ISSUE THREAD

**Issue by russtrotter** [jiscdev/lrw-udd-api#7]
In testing against the UDD 1.2.1 API endpoints on https://jiscv2.learninglocker.net/api/jisc/v1.2.1, the UPDATED_AT field is never returned for the creds we have in the LAP, SSP or OpenDash scopes.  UPDATED_DT *does* seem to be a valid field for sorting, but it's never returned in the JSON.

**Comment by michaelwebbjisc** [comment]
It is returned for my scope in 1.2.3 - I'll test in other scopes

**Comment by amason** [comment]
Reviewed and is working as expected. Closing.
